const Category = {
  Misc: "Misc",
  Groceries: "Groceries",
  Travel: "Travel",
  Social: "Social",
  Rent: "Rent",
  Utilities: "Utilities",
  Phone: "Phone",
  Clothes: "Clothes",
  Invoice: "Invoice",
  Gifts: "Gift",
};

const transactions = [
  {
    id: "1",
    amount: 50,
    type: "expense",
    description: "New Jeans",
    category: Category.Clothes,
    date: new Date("2021-08-01").getTime(),
  },
  {
    id: "2",
    amount: 10,
    type: "income",
    description: "Birthday gift",
    category: Category.Gifts,
    date: new Date("2021-08-05").getTime(),
  },
  {
    id: "3",
    amount: 15,
    type: "expense",
    description: "Shopping",
    category: Category.Groceries,
    date: "2021-08-10",
  },
  {
    id: "4",
    amount: 400,
    type: "income",
    description: "Work payment",
    category: Category.Invoice,
    date: new Date("2021-08-12").getTime(),
  },
  {
    id: "5",
    amount: 10,
    type: "expense",
    description: "New Headphones",
    category: Category.Misc,
    date: new Date("2021-08-12").getTime(),
  },
  {
    id: "6",
    amount: 40,
    type: "expense",
    description: "Phone bill",
    category: Category.Phone,
    date: new Date("2021-08-15").getTime(),
  },
  {
    id: "7",
    amount: 100,
    type: "expense",
    description: "Rent came",
    category: Category.Rent,
    date: new Date("2021-08-18").getTime(),
  },
  {
    id: "8",
    amount: 40,
    type: "expense",
    description: "BBQ at the park",
    category: Category.Social,
    date: new Date("2021-08-19").getTime(),
  },
  {
    id: "9",
    amount: 70,
    type: "expense",
    description: "Tube money",
    category: Category.Travel,
    date: new Date("2021-08-22").getTime(),
  },
  {
    id: "10",
    amount: 10,
    type: "expense",
    description: "Water and gas bill",
    category: Category.Utilities,
    date: new Date("2021-08-26").getTime(),
  },
];

module.exports = { transactions, Category };
